### ISSUE TITLE
SpeechRecognition issue

### ISSUE THREAD

**Issue by beaufortfrancois** [binomed/PrezWeb#45]
```js
Uncaught DOMException: Failed to execute 'start' on 'SpeechRecognition': recognition has already started.
    at VoiceRecognitionControler.start (http://localhost:3000/prez_bundle.js:679:30)
    at RevealEngineEvents._voiceCallBack (http://localhost:3000/prez_bundle.js:364:26)
    at HTMLElement.<anonymous> (http://localhost:3000/prez_bundle.js:350:12)

**Comment by beaufortfrancois** [comment]
Ca arrive quand je double clique sur "My Google Assistant" deux fois j'ai l'impression.

**Comment by jefBinomed** [comment]
oui en effet, j'ai pas de isBusy là :p
